from ply import lex, yacc

# -------------------
# ANALIZADOR LÉXICO
# -------------------

# Definición de tokens
tokens = (
    'IDENTIFICADOR', 'NUMERO', 'CADENA', 'CARACTER',
    'SUMA', 'RESTA', 'PRODUCTO', 'DIVISION', 'MODULO',
    'ASIGNACION', 'IGUALDAD', 'DIFERENTE', 'MENOR', 'MENOR_IGUAL',
    'MAYOR', 'MAYOR_IGUAL', 'Y_LOGICO', 'O_LOGICO', 'NEGACION',
    'PARENTESIS_IZQ', 'PARENTESIS_DER', 'LLAVE_IZQ', 'LLAVE_DER', 'CORCHETE_IZQ', 'CORCHETE_DER',
    'PUNTO_Y_COMA', 'COMA', 'PUNTO', 'DOS_PUNTOS',
    'INCREMENTO', 'DECREMENTO',
    'SUMA_ASIGNACION', 'RESTA_ASIGNACION', 'PRODUCTO_ASIGNACION', 'DIVISION_ASIGNACION',
    'SI', 'SI_NO', 'MIENTRAS', 'PARA', 'HACER', 'RETORNAR', 'SELECCIONAR', 'CASO',
    'INTERRUMPIR', 'CONTINUAR', 'POR_DEFECTO', 'IR_A', 'TIPO_DEF',
    'ESTRUCTURA', 'UNION', 'ENUMERACION', 'CONSTANTE', 'TAMANIO', 'ESTATICO',
    'VACIO', 'ENTERO', 'FLOTANTE', 'DOBLE'
)
